port: 8888
mirakurunPath: 'http://mirakurun:40772/'

dbtype: sqlite
sqlite:
   extensions:
     - '/usr/local/EPGStation/regexp.so'
   regexp: true

# dbtype: mysql
# mysql:
#     host: 192.168.xx.xx
#     port: 3306
#     user: epgstation
#     password: epgstation
#     database: epgstation

epgUpdateIntervalTime: 10

conflictPriority: 1
recPriority: 2

recordedFormat: '%YEAR%年%MONTH%月%DAY%日%HOUR%時%MIN%分%SEC%秒-%TITLE%'
recordedFileExtension: .ts
recorded:
    - name: recorded
      path: '%ROOT%/recorded'

thumbnail: '%ROOT%/thumbnail'
thumbnailSize: 480x270
thumbnailPosition: 5

ffmpeg: /usr/local/bin/ffmpeg
ffprobe: /usr/local/bin/ffprobe

isEnabledDropCheck: true
dropLog: '%ROOT%/recorded/droplog'

encodeProcessNum: 4
concurrentEncodeNum: 1
encode:
    - name: MP4
      cmd: '%NODE% %ROOT%/config/enc.js'
      suffix: .mp4
      rate: 4.0
    - name: MKV
      cmd: '%NODE% %ROOT%/config/enc-mkv.js'
      suffix: .mkv
      rate: 4.0

urlscheme:
    m2ts:
        ios: vlc-x-callback://x-callback-url/stream?url=PROTOCOL://ADDRESS
        android: intent://ADDRESS#Intent;package=org.videolan.vlc;type=video;scheme=PROTOCOL;end
    video:
        ios: infuse://x-callback-url/play?url=PROTOCOL://ADDRESS
        android: intent://ADDRESS#Intent;package=com.mxtech.videoplayer.ad;type=video;scheme=PROTOCOL;end
    download:
        ios: vlc-x-callback://x-callback-url/download?url=PROTOCOL://ADDRESS&filename=FILENAME

stream:
    live:
        ts:
            mp4:
                - name: 720p
                  cmd:
                      '%FFMPEG% -re -i pipe:0 -threads 0 -c:a copy 
                      -bsf:a aac_adtstoasc -c:v h264_omx -vf scale=-2:720 
                      -vb 3000k 
                      -movflags frag_keyframe+empty_moov+faststart+default_base_moof 
                      -y -f mp4 pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -re -i pipe:0 -threads 0 -c:a copy 
                      -bsf:a aac_adtstoasc -c:v h264_omx -vf scale=-2:480 
                      -vb 1500k 
                      -movflags frag_keyframe+empty_moov+faststart+default_base_moof 
                      -y -f mp4 pipe:1'

    recorded:
        ts:
            mp4:
                - name: 720p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0 
                      -c:a aac -ar 48000 -b:a 192k -ac 2 -c:v h264_omx 
                      -vf scale=-2:720 -b:v 3000k -movflags frag_keyframe+empty_moov+faststart+default_base_moof 
                      -y -f mp4 pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0 
                      -c:a aac -ar 48000 -b:a 128k -ac 2 -c:v h264_omx 
                      -vf scale=-2:480 -b:v 1500k -movflags frag_keyframe+empty_moov+faststart+default_base_moof 
                      -y -f mp4 pipe:1'

    encoded:
            mp4:
                - name: 720p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn 
                      -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2 
                      -c:v h264_omx -vf scale=-2:720 -b:v 3000k 
                      -movflags frag_keyframe+empty_moov+faststart+default_base_moof 
                      -y -f mp4 pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn 
                      -threads 0 -c:a aac -ar 48000 -b:a 128k -ac 2 
                      -c:v h264_omx -vf scale=-2:480 -b:v 1500k 
                      -profile:v baseline -preset veryfast 
                      -movflags frag_keyframe+empty_moov+faststart+default_base_moof 
                      -y -f mp4 pipe:1'

